version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 5000:5000
        environment:
            REDIS_HOST: redis
        volumes:
            - /var/app/venv
            - ./app:/var/app
    redis:
        image: redis:alpine
