version: "3.8"
services:
    redis:
        image: "redis:alpine"

    web:
        build: .
        expose:
            - 5000
        command: gunicorn --bind 0.0.0.0:5000 app:app
        environment:
            FLASK_ENV: production
        depends_on:
            - redis

    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - web
